name: "siglip_text_tokenize"
backend: "python"
max_batch_size: 32
default_model_filename: "siglip_text_tokenize.py"

input [
    {
        name: "INPUT_TEXT"
        data_type: TYPE_STRING
        dims: [1]
    }
]
output [
    {
        name: "INPUT_IDS"
        data_type: TYPE_INT64
        dims: [64]
    }
]

parameters: [
    {
        key: "EXECUTION_ENV_PATH",
        value: {string_value: "$$TRITON_MODEL_DIRECTORY/siglip_text_tokenize.tar.gz"},
    },
    {
        key: "default_truncation",
        value: {string_value: "false"},
    }
]
instance_group [
    {
        kind: KIND_CPU,
        count: 1
    }
]
version_policy: {latest: {num_versions: 1}}
dynamic_batching: {}