name: "siglip_text"
platform: "ensemble"
max_batch_size: 32

input [
    {
        name: "INPUT_TEXT"
        data_type: TYPE_STRING
        dims: [1]
    }
]
output [
    {
        name: "EMBEDDING"
        data_type: TYPE_FP32
        dims: [1152]
    }
]

ensemble_scheduling: {
    step: [
        {
            model_name: "siglip_text_tokenize"
            model_version: -1
            input_map {
                key: "INPUT_TEXT"
                value: "INPUT_TEXT"
            }
            output_map {
                key: "INPUT_IDS"
                value: "INPUT_IDS"
            }
        },
        {
            model_name: "siglip_text_model"
            model_version: -1
            input_map {
                key: "INPUT_IDS"
                value: "INPUT_IDS"
            }
            output_map {
                key: "EMBEDDING"
                value: "EMBEDDING"
            }
        }
    ]
}
